version: '3.8'

services:
  spark-installer:
    build: .
    volumes:
      - ./installation.py:/app/installation.py
    environment:
      - DISPLAY=host.docker.internal:0.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    privileged: true 